#!/usr/bin/env bash

# Fixed output directory
OUTPUT_DIR="."

CPP=cpp

INPUT_FILE=""
OUTPUT_NAME=""
OUTPUT_FORMAT="dtbo"

help() {
	echo "Usage: $0 --input <file> --name <file> [--output <dtb|dts|dtbo>]"
	echo ""
	echo "Options:"
	echo "  -i, --input         input .dts file"
	echo "  -n, --name          filename for output; without the extension"
	echo "  -o, --output        output format; defaults to $OUTPUT_FORMAT"
	echo "  -h, --help          display this help and exit"
	exit $1
}

if [ "$#" -le 2 ]; then
	help 1
fi

# Parse command line arguments
#
while [[ $# -gt 0 ]]; do
	case $1 in
		-i | --input )
			INPUT_FILE=$2
			shift 2
			;;
		-n | --name )
			OUTPUT_NAME=$2
			shift 2
			;;
		-o | --output )
			OUTPUT_FORMAT=$2
			shift 2
			;;
		-h | --help )
			help 0
			;;
		* )
			help 1
			;;
	esac
done

# Check if both input file and output file are provided
#
if [ -z "$INPUT_FILE" ] || [ -z "$OUTPUT_NAME" ]; then
	echo "error: no input file or output name"
	exit 1
fi

# Check if input file exists
#
if [ ! -f "$INPUT_FILE" ]; then
	echo "error: input file not found: '$INPUT_FILE'"
	exit 1
fi

# Check if output format is valid
#
case $OUTPUT_FORMAT in
	dtb | dtbo | dts )
		;;
	* )
		echo "error: invalid output format: '$OUTPUT_FORMAT'"
		exit 1
		;;
esac

OUTPUT_FILE="$OUTPUT_NAME.$OUTPUT_FORMAT"

OUTPUT_FILE_DIR=$(dirname $OUTPUT_FILE)
mkdir -p "$OUTPUT_DIR/$OUTPUT_FILE_DIR"

# Preprocess DTS file with arm-none-eabi-cpp and pipe the output to dtc to generate DTB or DTBO file
#
if [ "$OUTPUT_FORMAT" = "dts" ]; then
	# arm-none-eabi-cpp -nostdinc -I include -undef -x assembler-with-cpp "$INPUT_FILE" "$OUTPUT_DIR/$OUTPUT_FILE"
	$CC$CPP -nostdinc -I $KERNEL_DIR/include -undef -x assembler-with-cpp "$INPUT_FILE" "$OUTPUT_DIR/$OUTPUT_FILE"
else
	# arm-none-eabi-cpp -nostdinc -I include -undef -x assembler-with-cpp "$INPUT_FILE" | dtc -O dtb -o "$OUTPUT_DIR/$OUTPUT_FILE" -@
	$CC$CPP -nostdinc -I $KERNEL_DIR/include -undef -x assembler-with-cpp "$INPUT_FILE" | dtc -O dtb -o "$OUTPUT_DIR/$OUTPUT_FILE" -@
fi
