#obj-m := bd71837.o
#bd71837-y := bd71837-regulator.o mfd-bd71837.o clk-bd71837.o
#obj-m := mfd-bd71837.o
#obj-m += clk-bd71837.o
#obj-m += bd71837-regulator.o
obj-m += bd71837-test.o

all:
	make -C ${KERNEL_DIR} CROSS_COMPILE=${CC} ARCH=arm M=$(PWD) modules

clean:
	make -C ${KERNEL_DIR} CROSS_COMPILE=${CC} ARCH=arm M=$(PWD) clean

install:
	cp bd71837-test.ko  ${CFG_BBB_NFS_ROOT}/.
	cp bd71837_test.dtbo  ${CFG_BBB_NFS_ROOT}/.
	cp bbb_only_I2C_1.dtbo  ${CFG_BBB_NFS_ROOT}/.

debug_cfg:
	make -C ${KERNEL_DIR} CROSS_COMPILE=${CC} ARCH=arm M=$(PWD) CONFIG_DEBUG_SECTION_MISMATCH=y modules
