obj-m += bd71828_pd_test.o

all: bd71828-test dtb
bd71828-test: bd71828_pd_test.c
	make -C ${KERNEL_DIR} CROSS_COMPILE=${CC} ARCH=arm M=$(PWD) modules
dtb: ${DTS_FILE}
	dtc -O dtb -o bd71828_pd_test.dtbo -b 0 -@ ${DTS_FILE}

clean:
	rm -rf bd71828_test.dtbo
install:
	cp bd71828_pd_test.dtbo  ${CFG_BBB_NFS_ROOT}/.
	cp bd71828_pd_test.ko  ${CFG_BBB_NFS_ROOT}/.

debug_cfg:
	make -C ${KERNEL_DIR} CROSS_COMPILE=${CC} ARCH=arm M=$(PWD) CONFIG_DEBUG_SECTION_MISMATCH=y modules
