all:
	/home/kale/Linux-Driver-Testing/compilers/gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc accel_integrity_test.c -pthread -o accel_integrity_test
install:
	mv accel_integrity_test ~/nfs

